CREATE TABLE users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  password TEXT NOT NULL,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT NOT NULL,
  location TEXT NULL,
  website TEXT NULL,
  created_at TIMESTAMP DEFAULT now() NOT NULL,
  followers_count INTEGER NOT NULL,
  following_count INTEGER NOT NULL
);